source 'https://rubygems.org'
# ruby "2.1.8"

gem 'pry'
gem 'pry-nav'
# gem 'debugger'

gem 'bundler'

gem 'rake'

gem 'sinatra'

gem 'yajl-ruby'


gem 'ampex'

gem 'mongo'
gem 'moped', "1.5.1"
gem 'mongoid', "3.0.15"
gem 'bson_ext'

gem 'delayed_job'
gem 'delayed_job_mongoid', :path => 'vendor/gems/delayed_job_mongoid'

gem "enumerize", "~>0.8.0"
gem 'mongoid-tree', :path => 'vendor/gems/mongoid-tree'
gem 'voteable_mongo', :path=>'vendor/gems/voteable_mongo'
gem 'mongoid_magic_counter_cache', :path => 'vendor/gems/mongoid-magic-counter-cache' 

gem 'kaminari', :require => 'kaminari/sinatra', :path => 'vendor/gems/kaminari'

gem 'faker'
gem 'will_paginate_mongoid'
gem 'rdiscount'
gem 'nokogiri'

gem 'tire', "0.6.2"
gem 'tire-contrib'

gem 'dalli'

gem 'rest-client'

group :test do
  gem 'rspec'
  gem 'rack-test', :require => "rack/test"
  gem 'guard'
  gem 'guard-unicorn'
  gem 'simplecov', :require => false
  gem 'database_cleaner'
end

gem 'newrelic_rpm'
gem 'newrelic_moped'
gem 'unicorn'
gem "rack-timeout", "0.1.0beta3"
gem "i18n"
gem "rack-contrib", :path => 'vendor/gems/rack-contrib'
